# configuracion para crear la imagen
# instalamos la imagen node
FROM node:16
# indicamos donde se guardan los datos
# por convencion se indica app
WORKDIR /app 
# copiamos el package.json
# "*" todo lo demas que sigue, incluye todos los archivos
COPY package*.json ./
# instalamos las dependencias 
RUN npm install
# copiar el codigo
# . = fuente . = destino
COPY . .
# exponer solo un puerto
EXPOSE 8004
# comando que utilizamos para correr la imagen
CMD [ "npm","start" ]